### PR TITLE
Update document emteria for rock4

### PR DESCRIPTION
**Pull request by Smieschek**
###### Description of changes

Updated document entry emteria for rock4

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

### CODE REVIEW

**Comment by jack-ma** [comment]
the logo path is wrong(the path is case sensitive, also the committed file is png but the url is webp), please fit it.

**Comment by Smieschek** [comment]
Updated english page entry of emteria which fixes image path, thanks!

**Review by jack-ma — DISMISSED** [review]

**Comment by jack-ma** [comment]
Hi, @Smieschek 

This commit can not pass the [pre-commit](https://pre-commit.com/) check, could you fix the format and push the change to your branch? Once the automatic check is passed, your PR will be merged.

**Comment by Smieschek** [comment]
> Hi, @Smieschek
> 
> This commit can not pass the [pre-commit](https://pre-commit.com/) check, could you fix the format and push the change to your branch? Once the automatic check is passed, your PR will be merged.

@jack-ma sorry for the back and forth. I think I've got it this time. Thanks for your review :)

**Review by jack-ma — APPROVED** [review]

**Pull request merged**
