### PR TITLE
Add emteria for Rock 5B document

### PR DESCRIPTION
**Pull request by Smieschek**
###### Description of changes

Added third party image emteria for Rock 5B

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

### CODE REVIEW

**Comment by jack-ma** [comment]
Please also add it to the English page:

i18n/en/docusaurus-plugin-content-docs/current/rock5/alternative-os/5b-3rd-images.md

**Comment by Smieschek** [comment]
Added entry to english page, thanks!

**Review by jack-ma — APPROVED** [review]

**Comment by jack-ma** [comment]
Hi, @Smieschek 

This commit can not pass the [pre-commit](https://pre-commit.com/) check, could you fix the format and push the change to your branch? Once the automatic check is passed, your PR will be merged.

**Comment by Smieschek** [comment]
@jack-ma updated this as well, thank you :)

**Review by akgnah — APPROVED** [review]

**Pull request merged**
